### ISSUE TITLE
FAILED: ninja: 'Android.bp', needed by 'out/soong/build.aosp_rpi5_car.ninja', missing and no known rule to make it 18:12:16 soong bootstrap failed with: exit status 1

### ISSUE THREAD

**Issue by Aurotamizh** [raspberry-vanilla/android_local_manifest#104]
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# . build/envsetup.sh

root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# lunch aosp_rpi5_car-ap2a-userdebug

18:06:25 Build sandboxing disabled due to nsjail error.

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline mainline_module_prebuilt_nightly
TARGET_PRODUCT=aosp_rpi5_car
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a76
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.5.0-41-generic-x86_64-Ubuntu-22.04.4-LTS
HOST_CROSS_OS=windows
BUILD_ID=AP2A.240605.024
OUT_DIR=out
============================================

Want FASTER LOCAL BUILDS? Use -eng instead of -userdebug (however for performance benchmarking continue to use userdebug)
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# 
root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14# make bootimage systemimage vendorimage
18:11:48 Build sandboxing disabled due to nsjail error.
18:11:48 ************************************************************
18:11:48 You are building on a machine with 15.5GB of RAM
18:11:48 
18:11:48 The minimum required amount of free memory is around 16GB,
18:11:48 and even with that, some configurations may not work.
18:11:48 
18:11:48 If you run into segfaults or other errors, try reducing your
18:11:48 -j value.
18:11:48 ************************************************************
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline mainline_module_prebuilt_nightly
TARGET_PRODUCT=aosp_rpi5_car
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a76
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.5.0-41-generic-x86_64-Ubuntu-22.04.4-LTS
HOST_CROSS_OS=windows
BUILD_ID=AP2A.240605.024
OUT_DIR=out
============================================
FAILED: ninja: 'Android.bp', needed by 'out/soong/build.aosp_rpi5_car.ninja', missing and no known rule to make it
18:12:16 soong bootstrap failed with: exit status 1

#### failed to build some targets (30 seconds) ####

root@niyata-OptiPlex-7040:/media/niyata/287b9cf7-ca60-4131-9344-bf866f42dbc3/Sivaraman/Android14#

**Comment by ErikCopel** [comment]
@Aurotamizh Just create an Android.bp empty file on root directory, it should work.

**Comment by Aurotamizh** [comment]
Thanks @Konsta and @Erik
