### ISSUE TITLE
No "Debug over Wi-Fi" option on Developer Options (RPi5)

### ISSUE THREAD

**Issue by ErikCopel** [raspberry-vanilla/android_local_manifest#106]
I am unable to connect to adb over wi-fi

> failed to connect to '192.168.0.126:5555': Connection refused

**Comment by KonstaT** [comment]
Not quite how it works on any recent Android version (Android 11 and above). Please see e.g. https://developer.android.com/tools/adb.

**Comment by adufftpc** [comment]
@ErikCopel Have you tried to set the property (using USB for the first time)?
`adb shell setprop persist.adb.tcp.port 5555`

or add following to your .mk file?
```
PRODUCT_VENDOR_PROPERTIES += \
    persist.adb.tcp.port=5555
```
