### ISSUE TITLE
7inch raspberry pi touch screen with aosp 13 size problem 

### ISSUE THREAD

**Issue by rania-taabouri** [raspberry-vanilla/android_local_manifest#111]
I’m working on a project using a Raspberry Pi 4 with a custom Android 13 ROM and the official 7" Raspberry Pi touchscreen.
The touchscreen display is zoomed in, causing part of the display to be cut off and not fit the screen properly. The resolution settings do not seem to address this issue.
here is my config.txt file:
```
kernel=Image.gz
arm_64bit=1
dtparam=audio=on


# The functional overlay
dtoverlay=vc4-fkms-v3d-pi4-overlay,cma-256

# Touchscreen and backlight overlays
dtoverlay=rpi-ft5406-overlay 
dtoverlay=rpi-backlight-overlay

#dtoverlay=vc4-kms-dsi-7inch-overlay,sizex=800,sizey=480

# Additional settings
#dtoverlay=dwc2,dr_mode=peripheral
initramfs ramdisk.img followkernel
enable_uart=1
disable_overscan=1
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

display_rotate=0

# Enable the DSI display
ignore_lcd=0
display_default_lcd=1


# Display settings
framebuffer_width=800
framebuffer_height=480
gpu_mem=256

hdmi_group=2
hdmi_mode=87
hdmi_cvt=800 480 60 6 0 0 0
dtparam=spi=on
```

NB: both vc4-kms-v3d-pi4-overlay (white screen) and vc4-kms-dsi-7inch-overlay ( correct dtbo file generation problem or blocked in splash screen step) did not work for me that's why i am working with vc4-fkms-v3d-pi4-overlay,cma-256 overlay 

also tried with wm size command but it did not solve the problem

![450897194_507260078422029_3332747480816163803_n](https://github.com/user-attachments/assets/580546f6-3aaa-4648-9ee3-c4a6b643d69d)

**Comment by KonstaT** [comment]
Please read the relevant wiki page on how to use the official 7" Raspberry Pi DSI display.
https://github.com/raspberry-vanilla/android_local_manifest/wiki/DSI-display
