### ISSUE TITLE
My boot config.txt doesn't have # Boot device section

### ISSUE THREAD

**Issue by yjizhang** [raspberry-vanilla/android_local_manifest#114]
Hi, I download the aosp Android 14 code, and build successfully.
But after burn the image to sdcard/usb storage/nvme, there is no # Boot device section in /boot/config.txt.

**Comment by KonstaT** [comment]
There isn't supposed to be.

Closing as a duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/113.
