### ISSUE TITLE
Not able to connect USB debugging on Mac OS

### ISSUE THREAD

**Issue by ritik-datasembly** [raspberry-vanilla/android_local_manifest#115]
I was not able to detect respbarry pi 5 connect through the   my Macbook c-type port?
where as on my Ubuntu machine its easily able to detect the respbarry pi 5  USB device connect.
in both of the cases the USB debugging is ON.

**Comment by KonstaT** [comment]
Which would rather indicate an issue with the OS on your computer than Android on your Raspberry Pi.

I'm not a MacOS user so unfortunately I can't offer much assistance. USB vendor/product ids used on Raspberry Vanilla (https://github.com/raspberry-vanilla/android_device_brcm_rpi5/blob/android-14.0/usb/UsbGadget.cpp#L133-L184) are the same as on Google devices. Some generic ADB guides I can link:
https://developer.android.com/tools/adb
https://www.xda-developers.com/install-adb-windows-macos-linux/
