### ISSUE TITLE
Does RPI5 support AOSP 12?

### ISSUE THREAD

**Issue by yjizhang** [raspberry-vanilla/android_local_manifest#120]
I wanna run AOSP 12 on RPI5, can I just checkout AOSP 12 code and copy RPI5 kernel and device configs to make AOSP 12 work on RPI5?

**Comment by KonstaT** [comment]
Short answer would be no. Not saying it's impossible but can't find any reasonable reason why you would need to use an outdated Android version either.

Support for Pi 5 hardware was added in Pi Foundation's Linux 6.1 fork. Newest kernel version intended for Android 12 is 5.10.
