### ISSUE TITLE
Installing Google Apps (GApps) on Custom Android 13 ROM for Raspberry Pi 4

### ISSUE THREAD

**Issue by rania-taabouri** [raspberry-vanilla/android_local_manifest#121]
I’m experiencing issues with installing Google Apps (GApps) on my custom Android 13 ROM running on a Raspberry Pi 4. Specifically, I am unable to successfully install and run apps like the Play Store, Google Maps, and other Google services. Attempts to install these apps through APKPure result in crashes before the apps even start.

**Comment by KonstaT** [comment]
Google services is not part of Raspberry Vanilla project.

You can look into e.g. https://gitlab.com/MindTheGapps/vendor_gapps#build-inline-with-android to include GApps in your **personal** builds. Note that you're not allowed to distribute any Android image with Google services without acquiring GMS licensing (https://www.android.com/gms/).
