### ISSUE TITLE
AAOS RPi4 - BT Call initiated but no HFP audio on device - Android Automotive

### ISSUE THREAD

**Issue by nimesh-d** [raspberry-vanilla/android_local_manifest#127]
Device -  RPi4 8GB
version  android-14.0 

When making a phone call from connected cell phone or from recent calls screen in AAOS phone app,  call intiates and connects successfully.
But there is no HFP audio in RPi HDMI outs. 
Where as when playing media (like youtube) from phone, the A2DP audio works fine and I can here media audio from RPi HDMI output.

We have been stuck on this issue for months and would really appreciate any help to resolve the issue.
cc @KonstaT

**Comment by nimesh-d** [comment]
Call audio issue is present in Android-15 branch as well.

Also noticed the media audio paused immediately after starting. (This must be related to `a2dp_sink_automatically_request_audio_focus` property).
cc @KonstaT

**Comment by KonstaT** [comment]
> When making a phone call from connected cell phone or from recent calls screen in AAOS phone app, call intiates and connects successfully.
> But there is no HFP audio in RPi HDMI outs.
> Where as when playing media (like youtube) from phone, the A2DP audio works fine and I can here media audio from RPi HDMI output.

This has never worked. AFAIK Android bluetooth stack doesn't support SCO over HCI (vs. bluez stack on regular Linux distros). Also bluetooth hardware on Pi is not connected via PCM/I2S which I believe is quite commonly used for HFP.

Further reading (quite old but I don't think anything relevant has changed):
https://discuss.96boards.org/t/hfp-client-sco-audio-routing/3532/121
https://groups.google.com/g/btstack-dev/c/pZmp9QVWYBk
https://forums.raspberrypi.com/viewtopic.php?t=206970

> Also noticed the media audio paused immediately after starting.

Could be related to the commit I made following upstream configuration. It seems odd that both A2DP source and sink would be enabled at the same time. Likely defaults to source. You're welcome to revert the change in rpi4 device tree to see if it makes a difference.
https://github.com/raspberry-vanilla/android_device_brcm_rpi4/commit/741b658768af9b48058c9d6d2c32ade4bd158b98
https://android.googlesource.com/device/google_car/+/61473cb0ebd9e6071fa9e219be43651337fae752
https://android.googlesource.com/platform/packages/services/Car/+/c126f60c1bb6f0a557acecfefa6f4b6a54c10ead

**Comment by nimesh-d** [comment]
> > When making a phone call from connected cell phone or from recent calls screen in AAOS phone app, call intiates and connects successfully.
> > But there is no HFP audio in RPi HDMI outs.
> > Where as when playing media (like youtube) from phone, the A2DP audio works fine and I can here media audio from RPi HDMI output.
> 
> This has never worked. AFAIK Android bluetooth stack doesn't support SCO over HCI (vs. bluez stack on regular Linux distros). Also bluetooth hardware on Pi is not connected via PCM/I2S which I believe is quite commonly used for HFP.
> 
> Further reading (quite old but I don't think anything relevant has changed): https://discuss.96boards.org/t/hfp-client-sco-audio-routing/3532/121 https://groups.google.com/g/btstack-dev/c/pZmp9QVWYBk https://forums.raspberrypi.com/viewtopic.php?t=206970
> 
> > Also noticed the media audio paused immediately after starting.
> 
> Could be related to the commit I made following upstream configuration. It seems odd that both A2DB source and sink would be enabled at the same. Likely defaults to source. You're welcome to revert the change in rpi4 device tree to see if it makes a difference. [raspberry-vanilla/android_device_brcm_rpi4@741b658](https://github.com/raspberry-vanilla/android_device_brcm_rpi4/commit/741b658768af9b48058c9d6d2c32ade4bd158b98) https://android.googlesource.com/device/google_car/+/61473cb0ebd9e6071fa9e219be43651337fae752 https://android.googlesource.com/platform/packages/services/Car/+/c126f60c1bb6f0a557acecfefa6f4b6a54c10ead

Thank You!
