### ISSUE TITLE
Problem compile aosp car with raspberry pi 5 

### ISSUE THREAD

**Issue by nairdaweb** [raspberry-vanilla/android_local_manifest#128]
Hello, I am getting the following error during compilation. I have already tried it on Fedora and Debian, but it's always the same. I searched for these libraries and found nothing. I even installed all the SDKs, including Android Studio.

```
[100% 1156/1156] analyzing Android.bp files and generating ninja file at out/soong/build.aosp_rpi5_car.ninja
FAILED: out/soong/build.aosp_rpi5_car.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"    
 --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.aosp_rpi5_car.variables -o out/soong/build.aosp_rpi5_car.
ninja --globListDir aosp_rpi5_car --globFile out/soong/globs-aosp_rpi5_car.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.env
ironment.available --used_env out/soong/soong.environment.used.aosp_rpi5_car.build Android.bp
Warning: Module 'androidx.wear_wear' depends on non-existing optional_uses_libs 'wear-sdk'
Warning: Module 'androidx.wear.compose_compose-foundation' depends on non-existing optional_uses_libs 'wear-sdk'
09:40:38 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (05:42 (mm:ss)) ####
```

**Comment by KonstaT** [comment]
That doesn't actually give much insight why this failed. You'd probably need to dig into soong logs.

One possible reason is you just ran out of memory. Does your build machine meet the hardware requirements (https://source.android.com/docs/setup/start/requirements#hardware-requirements)? You could try adding a swap file or try bulding with a smaller number of parallel jobs (`make ... -jX`).

**Comment by KonstaT** [comment]
Closing as there's has been no update in a month. Assuming resolved using a build machine that meets the hardware requirements.
