### ISSUE TITLE
Android 12.1 support for RPi A 7″ touchscreen display 

### ISSUE THREAD

**Issue by Mustafa-AlHariry** [raspberry-vanilla/android_local_manifest#13]
Hello, 

I have a question 
Does android 12.1 support RPi Touch screen  ?

I have connected my touch screen to DSI and disconnect all HDMIs but a rainbow screen first appears then a black screen. 

Thanks in advance.

**Comment by KonstaT** [comment]
Please refer to the relevant wiki page.
https://github.com/raspberry-vanilla/android_local_manifest/wiki/DSI-display
