### ISSUE TITLE
Android 15 Build Error

### ISSUE THREAD

**Issue by aravinthkumarj1** [raspberry-vanilla/android_local_manifest#132]
I have tried to build for all the rpi4 target, I got same error while make.

`The following HALs in device manifest are not declared in FCM <= level 8: 
  android.hardware.camera.provider@2.5::ICameraProvider/legacy/0
  android.hardware.gatekeeper@1.0::IGatekeeper/default
  android.hardware.graphics.allocator@4.0::IAllocator/default
  android.hardware.graphics.composer@2.4::IComposer/default
  android.hardware.keymaster@4.1::IKeymasterDevice/default
  android.hardware.tv.cec@1.0::IHdmiCec/default
  android.hardware.usb.gadget@1.2::IUsbGadget/default
  android.hardware.wifi.supplicant.ISupplicant/default (@1)
ERROR: files are incompatible: android.hardware.camera.provider@2.5::ICameraProvider/legacy/0 is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.camera.provider@2.5::ICameraProvider/[^/]+/[0-9]+ from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.gatekeeper@1.0::IGatekeeper/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.gatekeeper@1.0::IGatekeeper/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.graphics.allocator@4.0::IAllocator/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.allocator@4.0::IAllocator/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.graphics.composer@2.4::IComposer/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.composer@2.1::IComposer/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.keymaster@4.1::IKeymasterDevice/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.keymaster@4.0::IKeymasterDevice/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.tv.cec@1.0::IHdmiCec/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.tv.cec@1.0::IHdmiCec/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.usb.gadget@1.2::IUsbGadget/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.usb.gadget@1.0::IUsbGadget/default from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.camera.provider@2.5::ICameraProvider/legacy/0 is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.camera.provider@2.5::ICameraProvider/[^/]+/[0-9]+ from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.gatekeeper@1.0::IGatekeeper/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.gatekeeper@1.0::IGatekeeper/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.graphics.allocator@4.0::IAllocator/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.allocator@4.0::IAllocator/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.graphics.composer@2.4::IComposer/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.composer@2.1::IComposer/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.keymaster@4.1::IKeymasterDevice/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.keymaster@4.0::IKeymasterDevice/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.tv.cec@1.0::IHdmiCec/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.tv.cec@1.0::IHdmiCec/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.usb.gadget@1.2::IUsbGadget/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.usb.gadget@1.0::IUsbGadget/default from /system/etc/vintf/compatibility_matrix.6.xml
android.hardware.camera.provider@2.5::ICameraProvider/legacy/0 is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.camera.provider@2.5::ICameraProvider/[^/]+/[0-9]+ from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.gatekeeper@1.0::IGatekeeper/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.gatekeeper@1.0::IGatekeeper/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.graphics.allocator@4.0::IAllocator/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.allocator@4.0::IAllocator/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.graphics.composer@2.4::IComposer/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.graphics.composer@2.1::IComposer/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.keymaster@4.1::IKeymasterDevice/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.keymaster@4.0::IKeymasterDevice/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.tv.cec@1.0::IHdmiCec/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.tv.cec@1.0::IHdmiCec/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.usb.gadget@1.2::IUsbGadget/default is deprecated in compatibility matrix at FCM Version 8; it should not be served.
    because it matches android.hardware.usb.gadget@1.0::IUsbGadget/default from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.wifi.supplicant@18446744073709551615.1::ISupplicant/default is deprecated; requires at least 18446744073709551615.2
    because it matches android.hardware.wifi.supplicant.ISupplicant/default (@1) from /system/etc/vintf/compatibility_matrix.7.xml
The following instances are in the device manifest but not specified in framework compatibility matrix: 
    android.hardware.camera.provider@2.5::ICameraProvider/legacy/0
    android.hardware.gatekeeper@1.0::IGatekeeper/default
    android.hardware.graphics.allocator@4.0::IAllocator/default
    android.hardware.graphics.composer@2.4::IComposer/default
    android.hardware.keymaster@4.1::IKeymasterDevice/default
    android.hardware.tv.cec@1.0::IHdmiCec/default
    android.hardware.usb.gadget@1.2::IUsbGadget/default
    android.hardware.wifi.supplicant.ISupplicant/default (@1)
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 8.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 8 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success
INCOMPATIBLE
00:27:53 ninja failed with: exit status 1
`

**Comment by KonstaT** [comment]
Please follow the steps in the instruction on how to compile i.e.
```
make bootimage systemimage vendorimage -j$(nproc)
```

Previously discussed in https://github.com/raspberry-vanilla/android_local_manifest/issues/25 & https://github.com/raspberry-vanilla/android_local_manifest/issues/34.
