### ISSUE TITLE
Disabling Private DNS on RPi4/AOSP15 has no effect

### ISSUE THREAD

**Issue by lollo0296** [raspberry-vanilla/android_local_manifest#136]
I have a local DNS Server on my network (PiHole).

With Private DNS set to Automatic (default settings) I actually expect my DNS-Server not to be used, as the OS is going to use encrypted public DNS-Servers. As expected, it does not work.

With Private DNS set to off instead, the OS should resolve domain names with my local DNS, but it doesn't. DNS setting can be given via DHCP or manually, it makes no differences at all. 

Furthermore, you can see under Wi-Fi connection info that some IPv6 DNS servers are still listed first, even if Private DNS is set to off,. Local DNS server is the last entry of the DNS list.

What is going on here? Cheers

**Comment by KonstaT** [comment]
Raspberry Vanilla project doesn't change the default AOSP behaviour in this regard or change the default Android DNS configuration.

For configuration issues it would be better to ask the PiHole community.
