### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by SiderM** [raspberry-vanilla/android_local_manifest#141]
Hello! You have created a wonderful project! I'm new to aosp assembly. I was able to build and run Android on my raspberry pi 4. Do you have instructions on how to remove the status bar and navigation bar so that I can run my application in full screen? As if in kiosk mode.

**Comment by KonstaT** [comment]
Please refer to AOSP documentation.
https://developer.android.com/develop/ui/views/layout/immersive
https://developer.android.com/work/dpc/dedicated-devices/lock-task-mode
