### ISSUE TITLE
add an unsigned custom apk into aosp build

### ISSUE THREAD

**Issue by lohriialo** [raspberry-vanilla/android_local_manifest#148]
I'm trying to add a custom launcher into aosp build, which would replace the default `HOME` launcher,  I've created a test apk from Android Studio and added the following to my apk manifest. This apk installs just fine in a manual install via adb, however with custom aosp build, everything compiles fine but custom launcher in nowhere to be found, on boot it defaults to aosp launcher, what have I done wrong?
```
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.HOME" />
    <category android:name="android.intent.category.DEFAULT" />

</intent-filter>
```
Here's what I've modified so far : Created a new folder called `MyLauncher` at  `/home/username/aosp/vendor/brcm` with the contents of `Android.bp` as below and `app-debug.apk ` in the same `MyLauncher` dir
```
soong_namespace {
}

android_app_import {
    name: "MyLauncher",
    owner: "Some Org Name",
    apk: "app-debug.apk",
    certificate: "platform",
    privileged: true,
    overrides: [
      "Home",
      "Launcher2",
      "Launcher3", 
      "Quickstep-V3", 
      "Launcher3QuickStep", 
      "Launcher3Go", 
      "Launcher3QuickStepGo",
      "Trebuchet",
      "TrebuchetQuickstep",
      "TrebuchetGo",
      "TrebuchetQuickstepGo"
    ],
    dex_preopt: {
	    enabled: false,
    },
}
```
And then I've defined the custom launcher in `/home/username/aosp/device/brcm/rpi5/aosp_rpi5.mk` like so
```
PRODUCT_PACKAGES += \
    AndroidRpiOverlay \
    SettingsRpiOverlay \
    SettingsProviderRpiOverlay \
    SystemUIRpiOverlay \
    WifiRpiOverlay \
    MyLauncher
```

**Comment by KonstaT** [comment]
Closing as this is not an issue with the Raspberry Pi device specific AOSP implementation Raspberry Vanilla project provides.

You can see AOSP for reference on how to use `android_app_import` in Android.bp.
https://cs.android.com/search?q=Android.bp%20android_app_import

I'd probably recommend taking it in smaller steps. Try including the application first before trying to override bunch of packages that don't exist. 'make MyLauncher' and see what it produces.
