### ISSUE TITLE
How to unlock the device?

### ISSUE THREAD

**Issue by kipade** [raspberry-vanilla/android_local_manifest#149]
Almost things work perfectly, except I can't run "adb remount", it says "Device must be bootloader unlocked".
If so, how to unlock it under ubuntu?
Or, if there was a way build a image with device unlocked? 
thanks

**Comment by KonstaT** [comment]
Duplicate of https://github.com/raspberry-vanilla/android_local_manifest/issues/47, https://github.com/raspberry-vanilla/android_local_manifest/issues/109 & https://github.com/raspberry-vanilla/android_local_manifest/issues/126.
