### ISSUE TITLE
Not showing the boot screen

### ISSUE THREAD

**Issue by jijith700** [raspberry-vanilla/android_local_manifest#15]
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]
[    0.000000] Linux version 5.15.98-v8-gd6913395e514 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb3[    0.000000] random: crng init done
[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.4
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000000ec00000, size 512 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000]   DMA32    [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000]   node   0: [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x00000000fbffffff]
[    0.000000] On node 0, zone DMA32: 19456 pages in unavailable ranges
[    0.000000] On node 0, zone DMA32: 16384 pages in unavailable ranges
[    0.000000] percpu: Embedded 29 pages/cpu s80216 r8192 d30376 u118784
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: Spectre-v2
[    0.000000] CPU features: detected: Spectre-v3a
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] CPU features: detected: Spectre-BHB
[    0.000000] CPU features: kernel page table isolation forced ON by KASLR
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] CPU features: detected: ARM errata 1165522, 1319367, or 1530923
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 996912
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:1920x1080M@60 smsc95xx.macaddr=E4:5F:01:43:42:4A vc_mem.meme[    0.000000] Dentry cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] Inode-cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x0000000037400000-0x000000003b400000] (64MB)
[    0.000000] Memory: 3347240K/4050944K available (16768K kernel code, 2142K rwdata, 7200K rodata, 1536K init, 1365K bss, 179416K reserved, 524288K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 49211 entries in 193 pages
[    0.000000] ftrace: allocated 193 pages with 3 groups
[    0.000000] trace event string verifier disabled
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Rude variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] irq_brcmstb_l2: registered L2 intc (/soc/interrupt-controller@7ef00100, parent irq: 10)
[    0.000000] kfence: initialized - using 2097152 bytes for 255 objects at 0x(____ptrval____)-0x(____ptrval____)
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000000] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000338] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=216000)
[    0.000376] pid_max: default: 32768 minimum: 301
[    0.000529] LSM: Security Framework initializing
[    0.000589] SELinux:  Initializing.
[    0.000893] Mount-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.000965] Mountpoint-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.002750] cgroup: Disabling memory control group subsystem
[    0.006869] rcu: Hierarchical SRCU implementation.
[    0.008355] EFI services will not be available.
[    0.009109] smp: Bringing up secondary CPUs ...
[    0.010580] Detected PIPT I-cache on CPU1
[    0.010654] CPU1: Booted secondary processor 0x0000000001 [0x410fd083]
[    0.012473] Detected PIPT I-cache on CPU2
[    0.012525] CPU2: Booted secondary processor 0x0000000002 [0x410fd083]
[    0.014113] Detected PIPT I-cache on CPU3
[    0.014163] CPU3: Booted secondary processor 0x0000000003 [0x410fd083]
[    0.014412] smp: Brought up 1 node, 4 CPUs
[    0.014467] SMP: Total of 4 processors activated.
[    0.014485] CPU features: detected: 32-bit EL0 Support
[    0.014500] CPU features: detected: 32-bit EL1 Support
[    0.014518] CPU features: detected: CRC32 instructions
[    0.014916] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.073660] CPU: All CPU(s) started at EL2
[    0.073799] alternatives: patching kernel code
[    0.075896] devtmpfs: initialized
[    0.090101] Enabled cp15_barrier support
[    0.090152] Enabled setend support
[    0.090181] KASLR enabled
[    0.090549] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.090593] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.104824] pinctrl core: initialized pinctrl subsystem
[    0.105962] DMI not present or invalid.
[    0.106648] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.111260] DMA: preallocated 1024 KiB GFP_KERNEL pool for atomic allocations
[    0.111596] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.112727] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.112857] audit: initializing netlink subsys (disabled)
[    0.113250] audit: type=2000 audit(0.112:1): state=initialized audit_enabled=0 res=1
[    0.113950] thermal_sys: Registered thermal governor 'step_wise'
[    0.114244] cpuidle: using governor menu
[    0.114520] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.114771] ASID allocator initialised with 32768 entries
[    0.114960] Serial: AMBA PL011 UART driver
[    0.130795] bcm2835-mbox fe00b880.mailbox: mailbox enabled
[    0.164624] raspberrypi-firmware soc:firmware: Attached to firmware from 2023-01-18T12:28:54, variant start_x
[    0.168641] raspberrypi-firmware soc:firmware: Firmware hash is 658f02cc8edcb68a568273f05d2b6ceede181e15
[    0.234305] bcm2835-dma fe007000.dma: DMA legacy API manager, dmachans=0x1
[    0.239786] vgaarb: loaded
[    0.240333] SCSI subsystem initialized
[    0.240609] usbcore: registered new interface driver usbfs
[    0.240679] usbcore: registered new interface driver hub
[    0.240770] usbcore: registered new device driver usb
[    0.241277] usb_phy_generic phy: supply vcc not found, using dummy regulator
[    0.241531] usb_phy_generic phy: dummy supplies not allowed for exclusive requests
[    0.242267] mc: Linux media interface: v0.10
[    0.242341] videodev: Linux video capture interface: v2.00
[    0.242515] pps_core: LinuxPPS API ver. 1 registered
[    0.242533] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.242579] PTP clock support registered
[    0.243128] Advanced Linux Sound Architecture Driver Initialized.
[    0.244986] clocksource: Switched to clocksource arch_sys_counter
[    0.347707] VFS: Disk quotas dquot_6.6.0
[    0.347849] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.348073] FS-Cache: Loaded
[    0.348399] CacheFiles: Loaded
[    0.349977] simple-framebuffer 3e402000.framebuffer: framebuffer at 0x3e402000, 0x7f8000 bytes
[    0.350005] simple-framebuffer 3e402000.framebuffer: format=a8r8g8b8, mode=1920x1080x32, linelength=7680
[    0.350279] simple-framebuffer 3e402000.framebuffer: fb0: simplefb registered!
[    0.352098] NET: Registered PF_INET protocol family
[    0.352588] IP idents hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.356087] tcp_listen_portaddr_hash hash table entries: 2048 (order: 3, 32768 bytes, linear)
[    0.356148] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.356180] TCP established hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.356389] TCP bind hash table entries: 32768 (order: 7, 524288 bytes, linear)
[    0.356842] TCP: Hash tables configured (established 32768 bind 32768)
[    0.357151] UDP hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.357231] UDP-Lite hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.357550] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.358419] PCI: CLS 0 bytes, default 64
[    0.359060] Trying to unpack rootfs image as initramfs...
[    0.379483] hw perfevents: enabled with armv8_cortex_a72 PMU driver, 7 counters available
[    0.379916] kvm [1]: IPA Size Limit: 44 bits
[    0.382077] kvm [1]: vgic interrupt IRQ9
[    0.382386] kvm [1]: Hyp mode initialized successfully
[    0.397467] Initialise system trusted keyrings
[    0.397956] workingset: timestamp_bits=46 max_order=20 bucket_order=0
[    0.408149] zbud: loaded
[    0.410832] fuse: init (API version 7.36)
[    0.458283] Freeing initrd memory: 1400K
[    0.475433] Key type asymmetric registered
[    0.475459] Asymmetric key parser 'x509' registered
[    0.475625] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 244)
[    0.476092] io scheduler mq-deadline registered
[    0.476117] io scheduler kyber registered
[    0.487368] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    0.487421] brcm-pcie fd500000.pcie:   No bus range found for /scb/pcie@7d500000, using [bus 00-ff]
[    0.487528] brcm-pcie fd500000.pcie:      MEM 0x0600000000..0x063fffffff -> 0x00c0000000
[    0.487635] brcm-pcie fd500000.pcie:   IB MEM 0x0000000000..0x00ffffffff -> 0x0400000000
[    0.551043] brcm-pcie fd500000.pcie: link up, 5.0 GT/s PCIe x1 (SSC)
[    0.551531] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
[    0.551557] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.551582] pci_bus 0000:00: root bus resource [mem 0x600000000-0x63fffffff] (bus address [0xc0000000-0xffffffff])
[    0.551686] pci 0000:00:00.0: [14e4:2711] type 01 class 0x060400
[    0.551992] pci 0000:00:00.0: PME# supported from D0 D3hot
[    0.556312] pci 0000:01:00.0: [1106:3483] type 00 class 0x0c0330
[    0.556452] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x00000fff 64bit]
[    0.557016] pci 0000:01:00.0: PME# supported from D0 D3hot
[    0.572383] pci 0000:00:00.0: BAR 8: assigned [mem 0x600000000-0x6000fffff]
[    0.572420] pci 0000:01:00.0: BAR 0: assigned [mem 0x600000000-0x600000fff 64bit]
[    0.572471] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.572502] pci 0000:00:00.0:   bridge window [mem 0x600000000-0x6000fffff]
[    0.583059] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.586388] iproc-rng200 fe104000.rng: hwrng registered
[    0.587003] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.588872] gpiomem-bcm2835 fe200000.gpiomem: Initialised: Registers at 0xfe200000
[    0.600863] fb0: switching to vc4 from simple
[    0.634289] vc4-drm gpu: bound fe400000.hvs (ops vc4_hvs_ops)
[    0.653719] brd: module loaded
[    0.666477] loop: module loaded
[    0.668075] Loading iSCSI transport class v2.0-870.
[    0.672115] wireguard: WireGuard 1.0.0 loaded. See www.wireguard.com for information.
[    0.672142] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    0.675476] tun: Universal TUN/TAP device driver, 1.6
[    0.676673] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    0.737167] unimac-mdio unimac-mdio.-19: Broadcom UniMAC MDIO bus
[    0.738423] PPP generic driver version 2.4.2
[    0.738713] PPP BSD Compression module registered
[    0.738736] PPP Deflate Compression module registered
[    0.738783] PPP MPPE Compression module registered
[    0.738803] NET: Registered PF_PPPOX protocol family
[    0.738823] PPTP driver version 0.8.5
[    0.739907] usbcore: registered new interface driver brcmfmac
[    0.739979] usbcore: registered new interface driver r8152
[    0.740063] usbcore: registered new interface driver lan78xx
[    0.740131] usbcore: registered new interface driver asix
[    0.740204] usbcore: registered new interface driver ax88179_178a
[    0.740264] usbcore: registered new interface driver cdc_ether
[    0.740346] usbcore: registered new interface driver smsc95xx
[    0.740406] usbcore: registered new interface driver net1080
[    0.740468] usbcore: registered new interface driver cdc_subset
[    0.740528] usbcore: registered new interface driver zaurus
[    0.740620] usbcore: registered new interface driver cdc_ncm
[    0.740680] usbcore: registered new interface driver r8153_ecm
[    0.740701] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.740721] ehci-pci: EHCI PCI platform driver
[    0.786797] pci 0000:00:00.0: enabling device (0000 -> 0002)
[    0.787008] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.787048] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    0.787898] xhci_hcd 0000:01:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0001e40000000890
[    0.789302] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.789331] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    0.789364] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    0.789865] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.15
[    0.789892] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.789913] usb usb1: Product: xHCI Host Controller
[    0.789932] usb usb1: Manufacturer: Linux 5.15.98-v8-gd6913395e514 xhci-hcd
[    0.789951] usb usb1: SerialNumber: 0000:01:00.0
[    0.790895] hub 1-0:1.0: USB hub found
[    0.790995] hub 1-0:1.0: 1 port detected
[    0.792198] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.15
[    0.792226] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.792246] usb usb2: Product: xHCI Host Controller
[    0.792265] usb usb2: Manufacturer: Linux 5.15.98-v8-gd6913395e514 xhci-hcd
[    0.792284] usb usb2: SerialNumber: 0000:01:00.0
[    0.793196] hub 2-0:1.0: USB hub found
[    0.793309] hub 2-0:1.0: 4 ports detected
[    0.795512] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.822281] dwc2 fe980000.usb: supply vusb_d not found, using dummy regulator
[    0.822558] dwc2 fe980000.usb: supply vusb_a not found, using dummy regulator
[    0.924506] dwc2 fe980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    0.925901] usbcore: registered new interface driver cdc_acm
[    0.925923] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    0.926342] usbcore: registered new interface driver uas
[    0.926477] usbcore: registered new interface driver usb-storage
[    0.926632] usbcore: registered new interface driver cp210x
[    0.926675] usbserial: USB Serial support registered for cp210x
[    0.926769] usbcore: registered new interface driver pl2303
[    0.926809] usbserial: USB Serial support registered for pl2303
[    0.927369] mousedev: PS/2 mouse device common for all mice
[    0.927495] usbcore: registered new interface driver xpad
[    0.927574] usbcore: registered new interface driver usb_acecad
[    0.927664] usbcore: registered new interface driver aiptek
[    0.927738] usbcore: registered new interface driver hanwang
[    0.927811] usbcore: registered new interface driver kbtab
[    0.927894] SPI driver ads7846 has no spi_device_id for ti,tsc2046
[    0.927912] SPI driver ads7846 has no spi_device_id for ti,ads7843
[    0.927928] SPI driver ads7846 has no spi_device_id for ti,ads7845
[    0.927944] SPI driver ads7846 has no spi_device_id for ti,ads7873
[    0.928143] usbcore: registered new interface driver usbtouchscreen
[    0.928875] i2c_dev: i2c /dev entries driver
[    0.930832] brcmstb-i2c fef04500.i2c:  @97500hz registered in polling mode
[    0.931684] brcmstb-i2c fef09500.i2c:  @97500hz registered in polling mode
[    0.933352] IR NEC protocol handler initialized
[    0.933375] IR RC5(x/sz) protocol handler initialized
[    0.933394] IR RC6 protocol handler initialized
[    0.933414] IR JVC protocol handler initialized
[    0.933432] IR Sony protocol handler initialized
[    0.933451] IR SANYO protocol handler initialized
[    0.933469] IR Sharp protocol handler initialized
[    0.933488] IR MCE Keyboard/mouse protocol handler initialized
[    0.933507] IR XMP protocol handler initialized
[    0.933525] ir_imon_decoder: IR iMON protocol handler initialized
[    0.933544] IR RCMM protocol handler initialized
[    0.934481] usbcore: registered new interface driver uvcvideo
[    0.938425] device-mapper: uevent: version 1.0.3
[    0.938847] device-mapper: ioctl: 4.45.0-ioctl (2021-03-22) initialised: dm-devel@redhat.com
[    0.943867] sdhci: Secure Digital Host Controller Interface driver
[    0.943892] sdhci: Copyright(c) Pierre Ossman
[    0.944730] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.949124] ledtrig-cpu: registered to indicate activity on CPUs
[    0.949301] hid: raw HID events driver (C) Jiri Kosina
[    0.953491] usbcore: registered new interface driver usbhid
[    0.953501] usbhid: USB HID core driver
[    0.954382] rpivid feb10000.codec: Device registered as /dev/video19
[    0.954997] ashmem: initialized
[    0.965510] bcm2835_audio bcm2835_audio: card created with 8 channels
[    1.044985] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    1.195629] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    1.195658] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    1.195680] usb 1-1: Product: USB2.0 Hub
[    1.197945] hub 1-1:1.0: USB hub found
[    1.198246] hub 1-1:1.0: 4 ports detected
[    1.285563] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    1.285594] [vc_sm_connected_init]: start
[    1.286269] [vc_sm_connected_init]: installed successfully
[    1.289269] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    1.289325] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    1.291784] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    1.291839] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    1.298053] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    1.298082] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    1.299863] bcm2835-codec bcm2835-codec: Device registered as /dev/video18
[    1.299898] bcm2835-codec bcm2835-codec: Loaded V4L2 image_fx
[    1.301928] bcm2835-codec bcm2835-codec: Device registered as /dev/video31
[    1.301955] bcm2835-codec bcm2835-codec: Loaded V4L2 encode_image
[    1.306345] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[    1.306661] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[    1.306922] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[    1.307146] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[    1.307171] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    1.307189] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    1.307206] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    1.307223] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    1.310048] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video20
[    1.310446] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video21
[    1.310865] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video22
[    1.311248] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video23
[    1.311272] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    1.311291] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    1.311307] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    1.311336] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    1.311476] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[    1.311608] SPI driver st-accel-spi has no spi_device_id for st,lis302dl-spi
[    1.311622] SPI driver st-accel-spi has no spi_device_id for st,lis3lv02dl-accel
[    1.311633] SPI driver st-accel-spi has no spi_device_id for st,lis3dh-accel
[    1.311645] SPI driver st-accel-spi has no spi_device_id for st,lsm330d-accel
[    1.311656] SPI driver st-accel-spi has no spi_device_id for st,lsm330dl-accel
[    1.311667] SPI driver st-accel-spi has no spi_device_id for st,lsm330dlc-accel
[    1.311679] SPI driver st-accel-spi has no spi_device_id for st,lis331dlh-accel
[    1.311689] SPI driver st-accel-spi has no spi_device_id for st,lsm330-accel
[    1.311700] SPI driver st-accel-spi has no spi_device_id for st,lsm303agr-accel
[    1.311712] SPI driver st-accel-spi has no spi_device_id for st,lis2dh12-accel
[    1.311723] SPI driver st-accel-spi has no spi_device_id for st,lng2dm-accel
[    1.311734] SPI driver st-accel-spi has no spi_device_id for st,h3lis331dl-accel
[    1.311745] SPI driver st-accel-spi has no spi_device_id for st,lis331dl-accel
[    1.311967] SPI driver st-magn-spi has no spi_device_id for st,lis3mdl-magn
[    1.311979] SPI driver st-magn-spi has no spi_device_id for st,lsm303agr-magn
[    1.311990] SPI driver st-magn-spi has no spi_device_id for st,lsm9ds1-magn
[    1.312051] SPI driver bmp280 has no spi_device_id for bosch,bmp085
[    1.312474] usbcore: registered new interface driver snd-usb-audio
[    1.319092] netem: version 1.3
[    1.319107] u32 classifier
[    1.319115]     input device check on
[    1.319122]     Actions configured
[    1.320533] xt_time: kernel timezone is -0000
[    1.320651] gre: GRE over IPv4 demultiplexor driver
[    1.320661] IPv4 over IPsec tunneling driver
[    1.321172] Initializing XFRM netlink socket
[    1.321205] IPsec XFRM device driver
[    1.321586] NET: Registered PF_INET6 protocol family
[    1.322851] Segment Routing with IPv6
[    1.322878] In-situ OAM (IOAM) with IPv6
[    1.322965] mip6: Mobile IPv6
[    1.323443] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    1.324202] NET: Registered PF_PACKET protocol family
0~�>>��Ύ>�>>�>~>�p����������p>�������>�������p�|�p�p0������������0>�p|�p�p�p�p�p��p0>>���p0���0���~>�~��p��>�>��p��>p0�|�������>�0�0|�p>�p>�~p>~p��p���>������>�>>�>>>��p0p�p>�>��>����p��0>�����������>p�.[    4.548059] init: Opening SELinux policy
[    4.555359] init: Falling back to standard signature check. TODO implementent support for fsverity SEPolicy.
[    4.565446] init: Error: Apex SEPolicy failed signature check

Control message: Could not find 'android.hardware.automotive.evs@1.1::IEvsEnumerator/hw/0' for ctl.interface_start from pid: 146 (/system/bin/hwservicemanager)
Control message: Could not find 'aidl/SurfaceFlingerAIDL' for ctl.interface_start from pid: 145 (/system/bin/servicemanager)

**Comment by KonstaT** [comment]
Closing this as Raspberry Vanilla doesn't offer Android Automotive build variant.

You can look into e.g. https://github.com/grapeup and https://github.com/rpi-aaos that are Android Automotive implementations based on Raspberry Vanilla.
