### ISSUE TITLE
Power Menu and Raspberry Pi Settings in Car Version

### ISSUE THREAD

**Issue by mbt28** [raspberry-vanilla/android_local_manifest#150]
Hello,

Automotive(aosp15) version doesn't respond keyboard f5 button for shutdown button. There is only restart option "Reset" menu. 

I tried to add RaspberryPI UI to aosp_rpi4_car-ap3a-userdebug but neither power_menu nor Raspberry PI setting menu appears. I tried to connect via wireless adb but device refuses the connection. 

How can I add raspberry pi settings and power menu to the build?

**Comment by KonstaT** [comment]
You would need to adjust keylayout if you wanted to map function keys to something else. E.g. for F5 to power key, you would change https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-15.0/keylayout/Generic.kl#L85 to key `63    POWER`.

My Raspberry Pi settings implementation is not part of Raspaberry Vanilla project. You can achieve the same result for most parts by following the project's documentation (https://github.com/raspberry-vanilla/android_local_manifest/wiki) or editing `config.txt` (GPIO buttons, CPU overclocking, etc).
