### ISSUE TITLE
an't open 'out/target/product/rpi4/kernel

### ISSUE THREAD

**Issue by RubinPro** [raspberry-vanilla/android_local_manifest#151]
[ 99% 158183/158567] Target boot debug image: out/target/product/rpi4/boot-debug.img (priority: 6)
FAILED: out/target/product/rpi4/boot-debug.img
/bin/bash -c "out/host/linux-x86/bin/mkbootimg --kernel out/target/product/rpi4/kernel  --ramdisk out/target
/product/rpi4/ramdisk-debug.img --cmdline \"console=ttyS0,115200 no_console_suspend root=/dev/ram0 rootwait 
androidboot.hardware=rpi4 androidboot.selinux=permissive\" --os_version 14 --os_patch_level 2024-05-05  --ou
tput  out/target/product/rpi4/boot-debug.img"
usage: mkbootimg [-h] [--kernel KERNEL] [--ramdisk RAMDISK] [--second SECOND]
                 [--dtb DTB]
                 [--recovery_dtbo RECOVERY_DTBO | --recovery_acpio RECOVERY_ACPIO]
                 [--cmdline CMDLINE] [--vendor_cmdline VENDOR_CMDLINE]
                 [--base BASE] [--kernel_offset KERNEL_OFFSET]
                 [--ramdisk_offset RAMDISK_OFFSET]
                 [--second_offset SECOND_OFFSET] [--dtb_offset DTB_OFFSET]
                 [--os_version OS_VERSION] [--os_patch_level OS_PATCH_LEVEL]
                 [--tags_offset TAGS_OFFSET] [--board BOARD]
                 [--pagesize {2048,4096,8192,16384}] [--id]
                 [--header_version HEADER_VERSION] [-o OUTPUT]
                 [--vendor_boot VENDOR_BOOT] [--vendor_ramdisk VENDOR_RAMDISK]
                 [--vendor_bootconfig VENDOR_BOOTCONFIG]
                 [--gki_signing_algorithm GKI_SIGNING_ALGORITHM]
                 [--gki_signing_key GKI_SIGNING_KEY]
                 [--gki_signing_signature_args GKI_SIGNING_SIGNATURE_ARGS]
                 [--gki_signing_avbtool_path GKI_SIGNING_AVBTOOL_PATH]
mkbootimg: error: argument --kernel: can't open 'out/target/product/rpi4/kernel': [Errno 2] No such file or 
directory: 'out/target/product/rpi4/kernel'
13:34:32 ninja failed with: exit status 1

**Comment by KonstaT** [comment]
Yet the kernel gets copied to `out/target/product/rpi4/kernel` in https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-14.0/device.mk#L201-L203.

Also `mkbootimg` is not used for anything in Raspberry Vanilla project as we're using a custom one.
https://github.com/raspberry-vanilla/android_build/commit/c075bf67ea7fae3231ddbfbba8dab86d2edd87e2
https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-14.0/BoardConfig.mk#L46-L47
https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-14.0/mkbootimg.mk

I can only assume you're doing something other than what is instructed in the project's documentation.
https://github.com/raspberry-vanilla/android_local_manifest

**Comment by RubinPro** [comment]
No, I have built it exactly according to the documentation provided on your GitHub and I still get this error.

source i downloaded
repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r34
curl -o .repo/local_manifests/manifest_brcm_rpi.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0.0_r34/manifest_brcm_rpi.xml --create-dirs

device i lunched
lunch aosp_rpi4-ap1a-userdebug

my out ls 

reza@reza-System-Product-Name:/mnt/9e003179-9ea9-41b3-9125-c356adfc3555/Aosprasberry12/AospRasberry14/out/target/product/rpi4$ ls -a
.				    installed-files-ramdisk.json
..				    installed-files-ramdisk.txt
all_modules.txt			    installed-files-root.json
android-info.txt		    installed-files-root.txt
apex				    obj
appcompat			    obj_arm
boot.img			    previous_build_config.mk
build_fingerprint.txt		    product_packages.txt
build_thumbprint.txt		    ramdisk
clean_steps.mk			    ramdisk-debug.img
.copied_headers_list		    ramdisk.img
debug_ramdisk			    ramdisk_node_list
dexpreopt_config		    root
fake_packages			    rpiboot
gen				    symbols
.installable_files.previous	    system
installed-files-ramdisk-debug.json  test_harness_ramdisk
installed-files-ramdisk-debug.txt   vendor

**Comment by KonstaT** [comment]
Judging by the output and the presence of `rpiboot` directory and `boot.img`, `make bootimage` has succeeded and you would never need host `mkbootimg` for anything.

So, we're still at I can only assume you're doing something other than what is instructed in the project's documentation (i.e. `make bootimage systemimage vendorimage`).
