### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by aurosiva** [raspberry-vanilla/android_local_manifest#159]
![Screenshot from 2024-12-13 20-22-05](https://github.com/user-attachments/assets/f7142e58-0422-438a-b869-b6bed65b54a4)
![Screenshot from 2024-12-13 20-22-05](https://github.com/user-attachments/assets/a0ccbab9-89fa-4086-9181-c37fbf5f83ed)
even after cloning tensorflow in external/ i get this issue while buiulding aosp 16 r6.

**Comment by KonstaT** [comment]
Please use code tags and copy the terminal output as text. Can't copy&paste from screenshots.

I have `external/tensorflow` and `external/federated-compute` in my source tree and can't reproduce such issue.

If you're suspecting that you haven't synced the source code properly, use `repo sync`. Don't clone anything manually.

We're currently at AOSP 15 (`android-15.0.0_r6`).

**Comment by aurosiva** [comment]
Hi @konsta

but i get these issue while syncing.

**Comment by KonstaT** [comment]
> but i get these issue while syncing.

I'm not going to start guessing. But yeah, I wouldn't expect it to compile if you haven't even successfully synced the source code.

**Comment by aurosiva** [comment]
@Konsta ,

Thanks man
