### ISSUE TITLE
Issue when compiling libdav1d for x86_64 Android

### ISSUE THREAD

**Issue by hmtheboy154** [raspberry-vanilla/android_local_manifest#16]
Hi, I am currently using your dav1d fork and building it on Bliss OS 15.8 (based on Android 12L). I've cloned it into `external/dav1d` and on ffmpeg I have the same changes like this commit 
https://github.com/raspberry-vanilla/android_external_ffmpeg/commit/3a9de769738258c5667fd947e8580a3cdb0ed946
But when I start to build, it gave me this error :  
```
FAILED: ninja: 'media/new-ej-drive/hmtheboy154/bliss15/out/target/product/x86_64/obj/MESON_LIBDAV1D/install/usr/local/lib/libdav1d.so', needed by '/media/new-ej-drive/hmtheboy154/bliss15/out/target/product/x86_64/obj/SHARED_LIBRARIES/libdav1d_intermediates/LINKED/libdav1d.so', missing and no known rule to make it
```

Is there anything wrong with my above setup that cause this error ?

**Comment by KonstaT** [comment]
I haven't tested to build for x86_64 so I'm not sure.

Double check that dav1d is enabled properly on the FFmpeg side (check the generated configs). There could be something arm specific on the dav1d Android makefile as well (e.g. https://github.com/raspberry-vanilla/android_external_dav1d/blob/android-13.0/android/meson_cross.mk#L67).

**Comment by KonstaT** [comment]
Closing as this is not directly related to AOSP on Raspberry Pi.
