### ISSUE TITLE
Facing Issues in building AAOS android-14.0.0_r22 for rpi4

### ISSUE THREAD

**Issue by BalajiPanneerselvam** [raspberry-vanilla/android_local_manifest#160]
Hi Team, 

I was previously using android-14.0.0_r22 branch for building AAOS for RPI4. Few days back i removed my local repo for a different reason. Today I tried downloading the same branch and build it again now but surprisingly i get the following build errors 

Steps  I tried to follow,
repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r22

curl -o .repo/local_manifests/manifest_brcm_rpi.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0.0_r22/manifest_brcm_rpi.xml --create-dirs

repo sync 
. build/envsetup.sh
lunch aosp_rpi4_car-userdebug
make bootimage systemimage vendorimage -j$(nproc)

Error I am encountering, 
[100% 1025/1025] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER" 
    --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --bazel-mode --globListDir build --globFile out/soong/globs-
build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.
build Android.bp
error: external/drm_hwcomposer/Android.bp:271:1: "com.android.hardware.graphics.composer.drm_hwcomposer" depends on undefined module "com.android.hard
ware.key".
Or did you mean ["com.android.hardware.usb"]?
error: external/drm_hwcomposer/Android.bp:271:1: "com.android.hardware.graphics.composer.drm_hwcomposer" depends on undefined module "com.android.hard
ware.certificate".
Or did you mean ["com.android.hardware.usb.certificate" "libcom.android.sysprop.bluetooth"]?
15:34:59 soong bootstrap failed with: exit status 1

**Comment by KonstaT** [comment]
Closing as using the outdated release tags are not supported or recommended. I've mainly created them for backup purposes when a new QRP is released. You can see from the device manifest (https://github.com/raspberry-vanilla/android_local_manifest/blob/android-14.0.0_r22/manifest_brcm_rpi.xml) what repositories are frozen to `android-14.0.0_r22 `and what are receiving further updates (i.e. `android-14.0`).

Apparently some recent drm_hwcomposer changes don't work with Android 14 QPR1. You can e.g. roll back the repository to where it was in April (https://github.com/raspberry-vanilla/android_external_drm_hwcomposer/tree/f5a9992ad0387b08753c799e8a5962e149f5bd71).

Rather just update to using `android-14.0` branch or even `android-15.0`.
