### ISSUE TITLE
Android support for Lilliput touch screen. 

### ISSUE THREAD

**Issue by Mustafa-AlHariry** [raspberry-vanilla/android_local_manifest#19]
Hello, 

Does the Android 12.1 on Raspberry Pi supports Lilliput touch screen? 

Thanks in advance

**Comment by KonstaT** [comment]
Brand name alone doesn't tell much. Generally speaking HDMI displays that use USB for touch interface are supported. Official Raspberry 7" DSI touchscreen is also supported. Waveshare HDMI displays that use SPI for touch interface are also supported. Waveshare DSI touchscreens are supported with Linux 6.1 kernel add-on.
