### ISSUE TITLE
Error When compile image

### ISSUE THREAD

**Issue by congnghe88** [raspberry-vanilla/android_local_manifest#20]
When I use command: make bootimage systemimage vendorimage -j$(nproc). I got many errors, these show below:

![image](https://github.com/raspberry-vanilla/android_local_manifest/assets/110919309/97c057cb-ee84-46a2-8d99-b7ec072e5e1e)

How i fix these errors.

**Comment by KonstaT** [comment]
Please follow the instructions on how to establish build environment.

You need to install libncurses5 which is part of the first step in the instruction (i.e. 1. Establish [Android build environment](https://source.android.com/setup/initializing)).

**Comment by congnghe88** [comment]
thanks a lot. I made it.
