### ISSUE TITLE
show internal problem message 

### ISSUE THREAD

**Issue by rdkartono** [raspberry-vanilla/android_local_manifest#24]
Tried flashing it.

After each reboot, android always show "There's an internal problem with your device. Contact your manufacturer for detail"

What might wrong ? Where to check what is the culprit ?

**Comment by KonstaT** [comment]
You would check 'logcat' output and relevant code:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-13.0.0_r67/services/core/java/com/android/server/wm/ActivityTaskManagerService.java#5826
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-13.0.0_r67/core/java/android/os/Build.java#1250

Or even disable such warning if you need to:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-13.0.0_r67/services/core/java/com/android/server/am/ActivityManagerService.java#8250
