### ISSUE TITLE
Need to get interface for Camera App

### ISSUE THREAD

**Issue by SarbeenaS** [raspberry-vanilla/android_local_manifest#27]
I need to get interface App to work with CSI Camera  connected on Raspberry PI 4 board flashed with Android image created using https://github.com/grapeup/aaos_local_manifest  
Any links or any inputs how to achieve that ?

Thanks,
Sarbeena

**Comment by KonstaT** [comment]
Raspberry Vanilla supports Android Automotive target in android-13.0 branch.
https://github.com/raspberry-vanilla/android_local_manifest/tree/android-13.0

CSI camera modules on Android Automotive target were also fixed when I added support for the EVS camera HAL.
https://github.com/raspberry-vanilla/android_device_brcm_rpi4/commit/d2d71de3513e3e985538e834e4ebb42084d4921b
