### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by candledragle** [raspberry-vanilla/android_local_manifest#3]
FAILED:
external/minigbm/gbm_mesa_driver/Android.mk: error: "libgbm_mesa_wrapper (SHARED_LIBRARIES android-arm64) missing liPOLICY_DIRS instead.bgbm_mesa (SHARED_LIBRARIES android-arm64)"                                                                         SEPOLICY_DIRS instead.
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/minigbm/gbm_mesa_driver/Android.mk: error: "libgbm_mesa_wrapper (SHARED_LIBRARIES android-arm) missing libgbgbm_mesa (SHARED_LIBRARIES android-arm64)" bm_mesa (SHARED_LIBRARIES android-arm)"                                                                             lems until later in the build.
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real probbm_mesa (SHARED_LIBRARIES android-arm)" lems until later in the build.                                                                                      lems until later in the build.
build/make/core/main.mk:1122: error: exiting from previous errors.
08:44:49 ckati failed with: exit status 1

#### failed to build some targets (07:27 (mm:ss)) ####

**Comment by KonstaT** [comment]
libgbm_mesa gets built from the mesa source (https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-13.0/BoardConfig.mk#L42, https://github.com/raspberry-vanilla/android_external_mesa3d/blob/android-13.0/android/Android.mk#L105, https://github.com/raspberry-vanilla/android_external_mesa3d/blob/android-13.0/android/Android.mk#L178-L181).

Closing this issue as this doesn't happen if you've set up the build environment and synced the source code as instructed (https://github.com/raspberry-vanilla/android_local_manifest/blob/android-13.0/README.md). No information was is provided if you've made some changes or trying to build something other that "vanilla" Raspberry Vanilla.
