### ISSUE TITLE
Need to launch EVS_APP from new icon added

### ISSUE THREAD

**Issue by SarbeenaS** [raspberry-vanilla/android_local_manifest#39]
I am able to launch EVS_APP using adb shell by giving command ./system/bin/evs_app. 
Attached 
![RaspberryEvs_App](https://github.com/raspberry-vanilla/android_local_manifest/assets/144411781/62844a07-58a7-4741-b84c-7d34334de0c2)

Now the requirement is to create  new app - Test_Evs_App as like EvsCameraPreview application and  EVS_APP (system/bin/evs_app) should be launched from this newly added Test_Evs_App application only.
I am able to create  new app - Test_Evs_App, but as of now internally its launching EvsCameraPreview application itself, instead it should call the actual system/bin/evs_app application. Any guidance how to achieve this?

Thanks,
Sarbeena

**Comment by KonstaT** [comment]
Closing as you vendor specific additions are not part of Raspberry Vanilla project.

You can contact me be email if you want to discuss hiring me for consulting/development work.
