### ISSUE TITLE
no aosp_rpi4-userdebug option

### ISSUE THREAD

**Issue by candledragle** [raspberry-vanilla/android_local_manifest#4]
Flow ReadMe 
I  do
repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r24 --depth=1
curl --create-dirs -L -o .repo/local_manifests/remove_projects.xml -O -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-13.0/remove_projects.xml

but I get 

(base) root@iZ0jldi7i29wyoldma6ofqZ:/mnt/pi4# . build/envsetup.sh
(base) root@iZ0jldi7i29wyoldma6ofqZ:/mnt/pi4# lunch aosp_rpi4-userdebug
[W][2023-01-15T19:43:21+0800][4240] logParams():267 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-01-15T19:43:21+0800][4240] logParams():277 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
In file included from build/make/core/config.mk:353:
In file included from build/make/core/envsetup.mk:354:
build/make/core/product_config.mk:228: error: Can not locate config makefile for product "aosp_rpi4".

(base) root@iZ0jldi7i29wyoldma6ofqZ:/mnt/pi4# lunch

You're building on Linux

Lunch menu .. Here are the common combinations:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_bluejay_car-userdebug
     4. aosp_bramble_car-userdebug
     5. aosp_car_arm-userdebug
     6. aosp_car_arm64-userdebug
     7. aosp_car_x86-userdebug
     8. aosp_car_x86_64-userdebug
     9. aosp_cf_arm64_auto-userdebug
     10. aosp_cf_arm64_phone-userdebug
     11. aosp_cf_x86_64_foldable-userdebug
     12. aosp_cf_x86_64_pc-userdebug
     13. aosp_cf_x86_64_phone-userdebug
     14. aosp_cf_x86_64_tv-userdebug
     15. aosp_cf_x86_auto-userdebug
     16. aosp_cf_x86_phone-userdebug
     17. aosp_cf_x86_tv-userdebug
     18. aosp_coral_car-userdebug
     19. aosp_flame_car-userdebug
     20. aosp_oriole_car-userdebug
     21. aosp_raven_car-userdebug
     22. aosp_redfin_car-userdebug
     23. aosp_sunfish_car-userdebug
     24. aosp_x86-eng
     25. aosp_x86_64-eng
     26. arm_krait-eng
     27. arm_v7_v8-eng
     28. armv8-eng
     29. armv8_cortex_a55-eng
     30. armv8_kryo385-eng
     31. car_ui_portrait-userdebug
     32. car_x86_64-userdebug
     33. gsi_car_arm64-userdebug
     34. gsi_car_x86_64-userdebug
     35. qemu_trusty_arm64-userdebug
     36. sdk_car_arm-userdebug
     37. sdk_car_arm64-userdebug
     38. sdk_car_portrait_x86_64-userdebug
     39. sdk_car_x86-userdebug
     40. sdk_car_x86_64-userdebug
     41. sdk_pc_x86_64-userdebug
     42. silvermont-eng
     43. uml-userdebug

Which would you like? [aosp_arm-eng]
Pick from common choices above (e.g. 13) or specify your own (e.g. aosp_barbet-eng):

**Comment by KonstaT** [comment]
Please follow the instructions (https://github.com/raspberry-vanilla/android_local_manifest/blob/android-13.0/README.md).

You haven't synced any of the Raspberry Pi specific code. This is mandatory!
```
curl --create-dirs -L -o .repo/local_manifests/manifest_brcm_rpi4.xml -O -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-13.0/manifest_brcm_rpi4.xml
```

The part that comes after that (reducing download size by creating a shallow clone and removing unneeded projects) is optional.
