### ISSUE TITLE
Can't control media volume on AOSP13 Android Automotive

### ISSUE THREAD

**Issue by Jeffreyan8** [raspberry-vanilla/android_local_manifest#40]
Hello,

I downloaded the source and compile for aosp_rpi4_car-userdebug and download the image.
I can't control music volume in settings -> sound

I'm OK that it can not be changed. But I need it maximum volum.
Now it's 25%.

In case of AOSP 13, it was 100%

Do you know how to set it to maximum?

Thanks,
Jeffrey,

**Comment by KonstaT** [comment]
Closing old AOSP13 related issues as we're currently at Android 15.

It's possible to adjust media volume on Android Automotive build from `android-15.0.0_r1` branch.
