### ISSUE TITLE
ld.lld: error: undefined symbol: std::__ndk1::__next_prime(unsigned long) Error while linking .a to EVS_APP

### ISSUE THREAD

**Issue by SarbeenaS** [raspberry-vanilla/android_local_manifest#45]
Android code was checked out from here:
https://github.com/raspberry-vanilla/android_local_manifest/tree/android-13.0 
 EVS_APP build successfully.

We build individually our CMakelist based application, using Android Studio NDK toolchain and created libPVIS_r.a file. For building the libPVIS_r.a, the below attached  script is used. 
![image](https://github.com/raspberry-vanilla/android_local_manifest/assets/144411781/98382a9d-f19b-4f0c-ab91-a351ffebc337)

This static lib  libPVIS_r.a is linked to EVS_APP using Android.bp file (/packages/services/Car/cpp/evs/apps/default/Android.bp) as follows:
![image](https://github.com/raspberry-vanilla/android_local_manifest/assets/144411781/2c644792-22b9-4bbb-b5c1-e2737160244c)
![image](https://github.com/raspberry-vanilla/android_local_manifest/assets/144411781/8f0a9a68-20f0-414e-9bf8-acee557c654b)

But while building EVS_APP, we are getting following error:
 **ld.lld: error: undefined symbol: std::__ndk1::__next_prime(unsigned long)
>>> referenced by __hash_table:2381 (/home/che7/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__hash_table:2381)**

Could you please help to understand what went wrong here?

Note : The same  libPVIS_r.a, if there is no function call to std::unordered_map from inside lib, the EVS_APP build is successful.

**Comment by KonstaT** [comment]
Closing as you vendor specific additions are not part of Raspberry Vanilla project.

You can contact me be email if you want to discuss hiring me for consulting/development work.
