### ISSUE TITLE
8 GB 

### ISSUE THREAD

**Issue by metl-play** [raspberry-vanilla/android_local_manifest#56]
That was on accident but as I am here,
my "problem" is, how to make the partition bigger than 8 GB to whatever I desire to do? Such as 110 GB would be more useful to me.

I compiled Android 14 for rPi4 8GB

**Comment by KonstaT** [comment]
You could create a larger image by editing https://github.com/raspberry-vanilla/android_device_brcm_rpi4/blob/android-14.0/mkimg.sh#L12.

I doubt you want to create 110GB image, though, so it would be easier just to mount the sdcard on your Linux machine and use e.g. GParted to extend the userdata partition to cover the unallocated space.
