### ISSUE TITLE
JDWP on RPi4 AOSP14 is unavailable

### ISSUE THREAD

**Issue by HZFrodo** [raspberry-vanilla/android_local_manifest#59]
I use RPi4 to do some apk debug works, but when I upgrade to AOSP14, JDWP is not working at all.
"adb jdwp" stucks and no output on AOSP14
But "adb jdwp" works well on AOSP13

Thanks for your excellent work to make AOSP work on RPi4 ;)

**Comment by KonstaT** [comment]
Android 14 changed some behaviour but seems to be working.
https://source.android.com/docs/setup/about/android-14-release#jdwp-threads
https://source.android.com/docs/core/runtime/configure#jdwp_options
