### ISSUE TITLE
if get_option('test') and 'vimc' not in pipelines

### ISSUE THREAD

**Issue by candledragle** [raspberry-vanilla/android_local_manifest#6]
Build started at 2023-01-16T17:49:15.058731
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /mnt/pi4/out/target/product/rpi4/obj/MESON_LIBCAMERA
Build dir: /mnt/pi4/out/target/product/rpi4/obj/MESON_LIBCAMERA/build
Build type: cross build

meson.build:127:33: ERROR: Expecting eol got not.
if get_option('test') and 'vimc' not in pipelines

**Comment by KonstaT** [comment]
You need meson version >= 0.55 (https://github.com/raspberry-vanilla/android_external_libcamera/blob/android-13.0/meson.build#L4, >= 0.53 is required for Mesa https://github.com/raspberry-vanilla/android_external_mesa3d/blob/android-13.0/meson.build#L29).

If you install meson from the snap package on Ubuntu 18.04 LTS as instructed (https://github.com/raspberry-vanilla/android_local_manifest/blob/android-13.0/README.md) you'll get meson 0.58.
