### ISSUE TITLE
TYPE-C is still not working in AOSP14-20240104-rpi5 version.

### ISSUE THREAD

**Issue by xulinkun** [raspberry-vanilla/android_local_manifest#61]
Hi, Konsta, I saw your latest version for rpi5, and it says USB-C (ADB, MTP, PTP, USB tethering) is ok. However, I've tried it and it still doesn't work. By the way, the Power Supply and ADB share a TYPE-C, I wonder how you use them?

**Comment by KonstaT** [comment]
There is no need to open a new issue when you've could have used your previous one.
https://github.com/raspberry-vanilla/android_local_manifest/issues/51

Most likely you haven't updated your EEPROM as required.
