### ISSUE TITLE
twrp no hdmi signal

### ISSUE THREAD

**Issue by thePublicer** [raspberry-vanilla/android_local_manifest#62]
when i reboot to twrp there was no signal

**Comment by KonstaT** [comment]
Closing as TWRP is not part of Raspberry Vanilla project.

You can look into e.g. https://github.com/twrp-raspberry/android_local_manifest/tree/twrp-11 to build TWRP for Raspberry Pi.

**Comment by thePublicer** [comment]
Okay, thank you!

**Comment by thePublicer** [comment]
I will describe the issue there
