### ISSUE TITLE
build AOSP14 failed, occurred  " 'meson'  is not allowed to be used "

### ISSUE THREAD

**Issue by xulinkun** [raspberry-vanilla/android_local_manifest#64]
As title say, then I add " meson:     Allowed, " into `build/soong/ui/build/paths/config.go`, it's ok. So I wonder whether this is a common problem and I think it's necessary to let you know.

**Comment by KonstaT** [comment]
Should not be a common problem as this is something I've never needed to address when setting my own build environment. Make sure you've followed the instructions on https://github.com/raspberry-vanilla/android_local_manifest/tree/android-14.0 including how to install meson.
