### ISSUE TITLE
Can't overclock the GPU on a Pi 4B

### ISSUE THREAD

**Issue by erayrafet** [raspberry-vanilla/android_local_manifest#65]
Well, running Android TV on the Pi 4B and overclocking the CPU and video decoders seems functional but v3d or gpu core clocks won't go above 450 MHz no matter what.
I did the config.txt edits on both Android TV 13 and 14.
![Screenshot_20240217-075914_Termux](https://github.com/raspberry-vanilla/android_local_manifest/assets/34194191/d25276f2-49eb-4de7-855c-079176889c4a)
![Screenshot_20240217-075839_Termux](https://github.com/raspberry-vanilla/android_local_manifest/assets/34194191/3d52a571-80cd-4f11-8ff1-b26f8caefdcf)

**Comment by KonstaT** [comment]
This is something that is handled on the firmware level and there's nothing Android specific here. Please refer to the Raspberry Pi documentation on the subject.
https://www.raspberrypi.com/documentation/computers/config_txt.html#overclocking-options

**Comment by erayrafet** [comment]
Sure but overclocking on PiOS worked. That's what's got me puzzled.

**Comment by KonstaT** [comment]
Something that could depend on e.g. Linux kernel version (6.1 vs. 5.15 in Android 14 & 13, respectively) and the boot firmware that matches the kernel version on my releases. I know that some of the options in your screenshot (e.g. `over_voltage`) are deprecated with recent Pi firmware.

**Comment by erayrafet** [comment]
I can't find any documentation about the firmware update changelogs but the results haven't changed in either Android 13 or 14. PiOS is on kernel 6.1 but the config.txt is in /boot/firmware now.
