### ISSUE TITLE
(rpi4b) LineageOS TV Andriod 14 HDMI blanking with PiP 

### ISSUE THREAD

**Issue by erayrafet** [raspberry-vanilla/android_local_manifest#66]
Running SmartTube with picture-in-picture makes the display blank out completely.
I gotta test other apps but seems like a ROM issue.

**Comment by KonstaT** [comment]
Closing as this issue tracker is for Raspberry Vanilla project.

Correct place for this would be where you got the build with appropriate logs (`logcat`) attached.
