### ISSUE TITLE
Unable to boot Android Automotive OS 14 on RPi 4B

### ISSUE THREAD

**Issue by swapnilrajharsh** [raspberry-vanilla/android_local_manifest#67]
Followed all the steps mentioned to generate the final image and also ensured the display port to be used is HDMI 0 port, but only black screen appears nothing else is visible.
Please find attached logs for your reference.
[rpi_a14r22.log](https://github.com/raspberry-vanilla/android_local_manifest/files/14527112/rpi_a14r22.log)

**Comment by KonstaT** [comment]
Please read https://github.com/raspberry-vanilla/android_local_manifest/wiki/HDMI-display.

You can use either HDMI port. You need to use a HDMI display that report resolutions it supports via EDID. If your display doesn't support `1920x1080` resolution, you need to adjust the build configuration as documented.

Seems to boot to Android according to the log (as far as `dmesg` can tell). You would need to post `logcat` output for more information.
