### ISSUE TITLE
AndroidRpiOverlay already defined

### ISSUE THREAD

**Issue by striork** [raspberry-vanilla/android_local_manifest#73]
First, Thanks for your hard work, of course! We wouldn't be able to do the things we do without people like you! 
 while attempting the car variant I got this error with exit status 1
step-1: we clone the repo using below commands
repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r30 --depth=1
curl -o .repo/local_manifests/manifest_brcm_rpi.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0/manifest_brcm_rpi.xml --create-dirs
curl -o .repo/local_manifests/remove_projects.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0/remove_projects.xml

step-2 : repo sync

step-3 : source 

build/envsetup.sh

step -4 : lunch aosp_rpi5_car-ap1a-userdebug
3.Compile
make bootimage systemimage vendorimage -j$(nproc)
This is where it went awry
=================================================================

wildcard(out/target/product/rpi5/clean_steps.mk) was changed, regenerating...
[ 89% 1027/1142] including out/soong/Android-aosp_rpi5_car.mk ...
FAILED: 
In file included from out/soong/installs-aosp_rpi5_car.mk:357511:
In file included from out/soong/Android-aosp_rpi5_car.mk:4333:
In file included from build/make/core/soong_app_prebuilt.mk:43:
build/make/core/base_rules.mk:292: error: device/brcm/rpi5/overlay/AndroidRpiOve
rlay: MODULE.TARGET.ETC.AndroidRpiOverlay already defined by overlay/AndroidRpiO
verlay.
17:04:06 ckati failed with: exit status 1

#### failed to build some targets (13 seconds) ####

tchort@pc:~/android14_pi5/android_device_brcm_rpi5-android-14.0$ 

![line 292](https://github.com/raspberry-vanilla/android_local_manifest/assets/100107900/04985c2d-c73d-4ebb-a4b6-b1c9dad4cad9)

**Comment by KonstaT** [comment]
From `tchort@pc:~/android14_pi5/android_device_brcm_rpi5-android-14.0$` I can only assume that you've also done something else that is not described above and not in the instructions on how to build (cloned the device tree for some reason?). Commands are also to be executed from the root directory of the AOSP source tree.
