### ISSUE TITLE
Recovery Image

### ISSUE THREAD

**Issue by redyana18** [raspberry-vanilla/android_local_manifest#77]
would you tell me how to build/add recovery image to be able to install the OTA package?
[Issue 69](https://github.com/raspberry-vanilla/android_local_manifest/issues/69#top)

**Comment by KonstaT** [comment]
Building recovery image and OTA packages is not on scope of Raspberry Vanilla project.

Here's how to build TWRP recovery for Raspberry Pi https://github.com/twrp-raspberry/android_local_manifest.
