### ISSUE TITLE
Audio and Bluetooth not working when installing with PINN

### ISSUE THREAD

**Issue by k2helix** [raspberry-vanilla/android_local_manifest#79]
I'm using [PINN](https://github.com/procount/pinn/) to be able to have two OSes installed in the same card. PINN includes LineageOS and its versions are avalaible to install without downloading it from https://konstakang.com/ (I'm aware there's a red "Do not mirror my builds" text, but I need to install more than one OS). I don't know if I should report this here or at PINN's issues.

I'm using a Raspberry Pi 5, and checked both in LOS 20 ATV and 21 ATV. There seems to be no HDMI audio, even when changing the audio output through Raspberry Settings available in the System tab. Bluetooth does detect devices but when clicking the pair button it will keep showing "Pairing" and ends up not connecting to any device (tried with bluetooth headphones and controller). The same setup works flawlessly when in Raspbian.

Everything else is working as intended, including 2.4 GHz peripherals.

If needed, I can provide logcat information (would be great if the log level and filter were specified)

**Comment by k2helix** [comment]
I took first look at `adb logcat` and here's what's I can see related to this problem in the output:

[atv.log](https://github.com/raspberry-vanilla/android_local_manifest/files/15049701/atv.log)

**Comment by KonstaT** [comment]
This issue tracker is mainly intended for people who are building from Raspberry Vanilla source code.

I'm not supporting any multi-boot solutions. Please follow the installation instructions on my website and if you can reproduce the issues, you're welcome to report it (e.g. comments on the release page of the specific build).
