### ISSUE TITLE
Not able to build android-14.0.0_r22 for target 'sdk_car_x86_64'

### ISSUE THREAD

**Issue by vaasuchavva** [raspberry-vanilla/android_local_manifest#80]
Hello konstakang,
Thanks for build and documentation.
we followed steps which are mentioned in

step-1: we clone the repo using below commands
repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r22
curl -o .repo/local_manifests/manifest_brcm_rpi.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0.0_r22/manifest_brcm_rpi.xml --create-dirs
curl -o .repo/local_manifests/remove_projects.xml -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-14.0.0_r22/remove_projects.xml

step-2 : repo sync
repo synced successfully
step-3 : source build/envsetup.sh
this is also success
step -4 : lunch sdk_car_x86_64-userdebug
step -5: make -j32

**FAILED**:
In file included from external/clang/Android.mk:92:
In file included from external/ffmpeg/Android.mk:21:
In file included from external/ffmpeg/libavcodec/Android.mk:15:
external/ffmpeg/libavcodec/../android/build.mk:43: error: external/ffmpeg/android/config-x86_64.mak: No such file or directory
11:49:48 ckati failed with: exit status 1

To fix this build failure, created config-x86_64.mak using actual content of file external/ffmpeg/android/config-armv8-a.mak and placed config-x86_64.mak at external/ffmpeg/android/ . Again the build failed and the build error is:
**FAILED**:
external/minigbm/gbm_mesa_driver/Android.mk: error: "libgbm_mesa_wrapper (SHARED_LIBRARIES android-x86_64) missing libgbm_mesa (SHARED_LIBRARIES android-x86_64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1135: error: exiting from previous errors.
11:55:53 ckati failed with: exit status 1

**Any idea what's going wrong here?**

Additional notes:
The goal is to create emulator image and setup AVD image in Android Studio for lunch target sdk_car_x86_64 using the source repo 'android-14.0.0_r22', which is setup as per the steps mentioned above. With the same repo able to build the flashable image for the device rpi5 (built using lunch target 'aosp_rpi5_car-userdebug').

**Comment by KonstaT** [comment]
Goal of the Raspberry Vanilla project is to provide AOSP device implementation for Raspberry Pi. Generic AOSP build targets (such as `sdk_car_x86_64-userdebug`) are not supported since it doesn't involve Raspberry Pi.

Just sync plain AOSP sources instead.
