### ISSUE TITLE
Trying to flash the image of aosp_14_rpi4 through usb and facing repeating logs 

### ISSUE THREAD

**Issue by devalapalli** [raspberry-vanilla/android_local_manifest#89]
Hello@konstaT
             We downloaded the android_14 image for rpi_4 through the below link 
              (https://dlupload.com/filedetail/631147552)
               we tried to boot through usb ,and after loading some logs ,the messsage of "Rebooting in 5 seconds "is repeating

Environment:
android version:14
Board :raspberry pi 4
Booting mode:USB 

please find attached file below
[Asop14_USB_16.txt](https://github.com/raspberry-vanilla/android_local_manifest/files/15330784/Asop14_USB_16.txt)
  if  any further details needed to address our issue please let us know.

THANK YOU.

**Comment by KonstaT** [comment]
This issue tracker is intended for people building from Raspberry Vanilla source code. You can find discussion for my personal builds on each release page.

Booting from USB devices is covered in the FAQ on each release page on my site.
