### ISSUE TITLE
USB/Wireless debugging on RP4 OR RP5

### ISSUE THREAD

**Issue by mahesh-embedded** [raspberry-vanilla/android_local_manifest#91]
Hello @KonstaT ,

Thank you for your efforts in porting AOSP to the Raspberry Pi.

I have couple of questions.
1) Is there any way to enable usb debugging ?
2)Wireless debugging is working fine in tablet but its not working android automotive build (android-14.0.0_r22).

for android automotive i would like to enable wireless debugging. it would be great if you can share any referances for that 

Thanks
Mahesh

**Comment by aladin153** [comment]
Hello,

I encoutered the same issue using android automotive build (android-14.0.0_r22). (Wireless debugging not working)

From serial logs, i found that adbd daemon is not started :
[   61.289412] init: Control message: Processed ctl.stop for 'adbd' from pid: 764 (system_server)
=> Checked also with ps -A (no process adbd)

I was able to enable adb over Wifi by adding this lines to init.rpi5.rc file :
on boot
    setprop service.adb.tcp.port 5555
    start adbd

Thanks.
Alaeddine
