### ISSUE TITLE
Error in modification of init.rc

### ISSUE THREAD

**Issue by alemig97** [raspberry-vanilla/android_local_manifest#97]
Hi, I wanted to try adding “stress-ng” to run at system reboot (I placed the stress-ng executable in the shell, and it works at runtime). However, after modifying the init.rc file, the system no longer functions properly. Is there another way to achieve this, or is it not allowed?

**Comment by KonstaT** [comment]
It's allowed but not good practice at least.

You can add your own init fragments e.g. to `/vendor/etc/init/` directory. You can use other files in that directory as a reference.
